repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.19.0
  hooks:
    - id: terraform_fmt
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
